#
# application.yml — главный конфигурационный файл Spring Boot.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml

jwt:
  secret-key: ChangeMeToAStrongKey
  validity-ms: 3600000

server:
  port: 8080